
/* Modelagem Básica */ 
ENTIDADE = TABELA
CAMPOS = ATRIBUTO

CLIENTE

NOME - CHAR(30)
CPF - INT(11)
EMAIL - CHAR(11)
TELEFONE - CHAR(30)
ENDERECO - CHAR(100)
SEXO CHAR - (1)

/* PROCESSOS DE MODELAGEM*/ 
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - SOFTWARE DE MODELAGEM(STARUML)


/* MODELAGEM FISICA*/
 
 CREATE DATABASE PROJETO;
 
 /*CONECTANDO AO BANCO */
 USE PROJETO;
 
 /*CRIANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/*VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;

/* INSERINDO NA TABELA*/
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF, EMAIL) VALUES ('MARIA', 'F', 'ESTRADA DO CATONHO', '24564858', '33333', 'MARIA@GMAIL.COM');
	
		
		

/*SELECT -> É O COMANDO DE PROJEÇÃO E NÃO DE SELECIONAR


/*COLUNA DATA_HORA COM NOW()'DIA E HORA' E COLUNA PROGRAMADOR COM 'MARCELLO LIMA'*/
SELECT NOW() AS DATA_HORA, 'MARCELLO LIMA' AS 'PROGRAMADOR'; 

/* ALIAS DE COLUNA*/
 SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE; /* COLUNA NOME PROJETA COMO 'CLIENTE'*/

 /*WHERE(ONDE) -> É O COMANDO DE SELEÇÃO*/
 
 /* FILTRANDO DADOS COM WHERE E LIKE*/
 
/*FILTRANDO*/ 
/* SELECIONE OS CAMPOS DA TABELA CLIENTE ONDE O SEXO SEJA = 'M'*/
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M';
 
/* SELECIONE OS CAMPOS DA TABELA CLIENTE ONDE O SEXO SEJA = 'F'*/
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

/*UTILIZANDO O LIKE*/

/*projete os campos da tabela cliente onde endereco tenha catonho em qualquer parte*/
SELECT NOME,SEXO,ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%DA%';

/*projete os campos da tabela cliente onde endereco tenha catonho no final*/
SELECT * FROM CLIENTE WHERE ENDERECO LIKE '%CATONHO';

/*projete os campos da tabela cliente onde endereco tenha SU NO INICIO*/
SELECT * FROM CLIENTE WHERE ENDERECO LIKE 'SU%';



 
 