CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(50),
	SEXO_AUTOR CHAR(1),
	NUM_PAGINA INT(11),
	NOME_EDITORA VARCHAR(50),
	VALOR_LIVRO FLOAT(24),
	UF_EDITORA CHAR(2),
	ANO_PUBLICACAO INT(4)
);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAGINA, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO ) VALUES ('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);
INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAGINA, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO ) 
VALUES ('SQL PARA LEIGOS', 'JOÃO NUNES', 'M', 450, 'ADDISON', 98, 'SP', 2018),
		('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);
	
INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAGINA, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO ) 
VALUES ('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018),
					('HABITOS SAUDÁVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', 150.98, 'RJ', 2019),
						('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016),
							('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 100, 'ES', 2015),
								('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 78.98, 'ES', 2011),
									('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018),
										('O PODER DA MENTE', 'CLARA MAGRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017);


/*TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/*TRAZER O NOME DO LIVRO E O NOME DA EDITORA*/
SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/*TRAZER O NOME DO LIVRO E A UF DA TABELA LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO*/ 
SELECT NOME_LIVRO, UF_EDITORA FROM LIVROS WHERE SEXO_AUTOR='M';

/*TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/
SELECT NOME_LIVRO, NUM_PAGINA FROM DA TABELA LIVROS WHERE SEXO_AUTOR='F';

/*TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SAO PAULO*/
SELECT VALOR_LIVRO FROM LIVROS WHERE UF_EDITORA='SP';

/*TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SAO PAULO OU RIO DE JANEIRO*/
SELECT NOME_AUTOR, SEXO_AUTOR, UF_EDITORA FROM LIVROS WHERE SEXO_AUTOR='M' AND (UF_EDITORA='RJ' OR UF_EDITORA='SP'); 